### PR TITLE
Devshm

### PR DESCRIPTION
**Pull request by adammoody**
Switch default cache and control directories from /tmp to /dev/shm.  The control directory must be in a node-local location and it should really be in ramdisk, because files are frequently accessed.  Also, it's good to pick a well-known node-local option.  Usually /tmp is defined on all Linux clusters, but it is not always node-local nor is it always shared memory.  The /dev/shm mount makes for a better option at this point.

This PR is currently noisy because it's based on https://github.com/LLNL/scr/pull/166

### CODE REVIEW

**Comment by adammoody** [comment]
Currently, I left the directories example text referring to /tmp, since the diagram shows /tmp.  If we change the diagram, we can then update the text.

**Comment by adammoody** [comment]
@kosinovsky , do you know if this change will happen to break any tests?

**Comment by adammoody** [comment]
@CamStan , do you know if this change breaks our existing tests?

**Comment by CamStan** [comment]
@adammoody, nothing is coming to mind that would cause this to break them. However, @kosinovsky is far more familiar with the tests than I am at this point.

**Comment by kosinovsky** [comment]
@adammoody, @CamStan it looks right to me

**Pull request merged**
