### PR TITLE
Docs: update to latest doc deps

### PR DESCRIPTION
**Pull request by CamStan**
Update the jinja2 version due to the Dependabot alert.

Updating the rest of the doc deps to their latest versions.

### CODE REVIEW

**Comment by mcfadden8** [comment]
Thanks @CamStan - Do we have a way of testing this prior to merging?  Is there a link that we can go to that will show what the documents will look like with these updates?

**Comment by CamStan** [comment]
> Do we have a way of testing this prior to merging? Is there a link that we can go to that will show what the documents will look like with these updates?

I usually do test it before bigger changes, but didn't this time. I'll do it real quick and provide the link

**Comment by CamStan** [comment]
@mcfadden8, I pushed the updated _requirements.txt_ file to my test-docs repo [here](https://github.com/CamStan/test-docs/commit/0ff5694f95eb91a42e3f49bc55be188c8e35e3a3), where both sets of docs get built using the same requirements file.

SCR docs test build: https://readthedocs.org/projects/camstan-test-docs-scr/builds/23173907/
SCR Developer docs test build: https://readthedocs.org/projects/camstan-test-docs-scrdev/builds/23173905/

Here is them both rendered:
SCR docs: https://camstan-test-docs-scr.readthedocs.io/en/latest/
SCR Developer docs: https://camstan-test-docs-scrdev.readthedocs.io/en/latest/

**Comment by CamStan** [comment]
There is a way to tell ReadTheDocs to build doc changes from pull requests and have it as a required check before merging. I played with this a couple months ago with UnifyFS, but have yet to get it to work properly. It's a new feature, so might be getting things ironed out still.

**Review by mcfadden8 — APPROVED** [review]
This looks good @CamStan, thanks for doing this and for testing to make sure the tools still built what we expect.

**Pull request merged**
