### PR TITLE
Move axl mpi to axl

### PR DESCRIPTION
**Pull request by mcfadden8**
This relates to [#489](https://github.com/LLNL/scr/issues/489)
The relates to AXL PR: https://github.com/ECP-VeloC/AXL/pull/129

### CODE REVIEW

**Comment by adammoody** [comment]
This one is hard to test until we start to merge things, but we'll want to remember to move this line:

https://github.com/LLNL/scr/blob/d153d585f8d3aef119d0986afd7b5642805270df/dist/CMakeLists.txt#L274

**Comment by mcfadden8** [comment]
> This one is hard to test until we start to merge things, but we'll want to remember to move this line:
> 
> https://github.com/LLNL/scr/blob/d153d585f8d3aef119d0986afd7b5642805270df/dist/CMakeLists.txt#L274

Nice catch!  I mistakenly left that in.  I also need to modify the dist script to include MPI=On when building AXL (if needed).  Let me change that now

**Comment by mcfadden8** [comment]
@adammoody, for dist, do I need to create both a noMPI library in addition to one with MPI enabled (similar to what is being done for other libraries like redset and others?

**Comment by adammoody** [comment]
> @adammoody, for dist, do I need to create both a noMPI library in addition to one with MPI enabled (similar to what is being done for other libraries like redset and others?

Yeah, I was just looking at that.  I think we will need to create a noMPI section for AXL, since we use AXL in the serial executables, which should not have MPI.  Maybe just copy the kvtree pattern again.

This should be easier to test when we merge the AXL PR.

**Review by adammoody — APPROVED** [review]

**Pull request merged**
