### PR TITLE
Update min cmake version to 3.14.5

### PR DESCRIPTION
**Pull request by mcfadden8**

### CODE REVIEW

**Comment by mcfadden8** [comment]
@adammoody - I think I remember that the version number stuff was discussed during one of our last meetings.  While 3.14.5 is still a little old, I think it is probably a good minumum requirement.

Do you agree?

**Comment by adammoody** [comment]
Thanks, @mcfadden8 .  Yes, I think this version is good.

We'll have some other scattered references to cmake versions around, like in the doc directory:

https://scr.readthedocs.io/en/v3.0/users/build.html#dependencies

Maybe we'd need to update our cmake version in our SCR spack package?

@gonsie may know of others.

**Comment by adammoody** [comment]
Sorry @mcfadden8 , I clobbered your change here with my ``scrConfig.cmake`` addition.

**Comment by mcfadden8** [comment]
@adammoody, what did we decide that the supported version of `cmake` should be?  I'm happy to submit another PR if we have decided.

**Comment by mcfadden8** [comment]
> @adammoody, what did we decide that the supported version of `cmake` should be? I'm happy to submit another PR if we have decided.

Nevermind @adammoody, I see that we did decide thtat 3.14.5 was okay.

**Comment by mcfadden8** [comment]
This relatest to problem issue #530

**Comment by mcfadden8** [comment]
@adammoody and @gonsie  - I think this is ready for review now.  I've updated the documentation as well as the cmake file.  I checked and did not see anything in the spack package that was checking for cmake versions.

**Comment by adammoody** [comment]
Thanks @mcfadden8 .  Looks good.  Would you also please update the dist CMakeLists.txt file?

https://github.com/LLNL/scr/blob/ea88597cb78fa5c109b87819ac2d17a45c881f10/dist/CMakeLists.txt#L1

**Comment by mcfadden8** [comment]
Done.  Sorry, I don't know why I keep forgetting about dist.

**Comment by adammoody** [comment]
Thanks.  No problem.  I keep forgetting about dist myself.

**Review by adammoody — APPROVED** [review]

**Comment by adammoody** [comment]
Thanks, @mcfadden8

**Pull request merged**
