### PR TITLE
modify some config settings for components

### PR DESCRIPTION
**Pull request by adammoody**

### CODE REVIEW

**Comment by adammoody** [comment]
@rhass80, that first commit has a couple tweaks to the config settings in scr.  Just wanted to run those by you.

**Comment by rhaas80** [comment]
> @rhass80, that first commit has a couple tweaks to the config settings in scr. Just wanted to run those by you.

gah. I had thought I had by now removed all instances where I had used `scr_debug` to set some component parameter that was not DEBUG. Ouch.

**Comment by rhaas80** [comment]
The changes seem ok though. At least nothing that obviously seem off. The code using `strdup(scr_flush_type)` relies on `scr_flush_type` never being `NULL` which is indeed true in the version.

**Comment by rhaas80** [comment]
It may be better to actually have a `#define SCR_MKDIR` for the default value of `MKDIR` being passed to AXL instead of hard-coding the value of `0` as done in the commits in this pull request.

**Comment by adammoody** [comment]
> 
> 
> It may be better to actually have a `#define SCR_MKDIR` for the default value of `MKDIR` being passed to AXL instead of hard-coding the value of `0` as done in the commits in this pull request.

Good point.  For background, I had hardcoded this to be 0 because SCR creates the directories so that we don't need AXL to create them again.  It turns out we did have an ``SCR_MKDIR`` that we weren't making use of.  I decided to rename that to ``SCR_AXL_MKDIR``.  One can now use that to toggle the setting that SCR passes to AXL, so one can now optionally ask AXL to create the directories.  When enabling AXL to create directories, it would make sense to disable SCR from creating them.  I may opt to save that change for a later PR.  For now, enabling this option will just end up with both SCR and AXL creating directories -- inefficient, but should work.

**Comment by adammoody** [comment]
> 
> 
> The changes seem ok though. At least nothing that obviously seem off. The code using `strdup(scr_flush_type)` relies on `scr_flush_type` never being `NULL` which is indeed true in the version.

Yes, good eye.  I had thought of adding an ``if scr_flush_type == NULL then abort`` type of check, but I figured this variable should always be defined.  If someone makes a future change where it could be NULL, then we'll segfault here, which acts like an abort.  Decided to just write it that way to keep the code concise.  I'll take another look.

**Pull request merged**
