### PR TITLE
update test_api_multiple to v1.2 API

### PR DESCRIPTION
**Pull request by adammoody**

### CODE REVIEW

**Comment by adammoody** [comment]
This updates test_api_multiple to use the latest API.  It also fixes the example so that it runs even with a single process.

Rather than update the test_*_file variants, this drops those for now.  They are nearly identical to test_api and test_api_multiple.  To bring them back, it'd be better to look at adding the necessary code to the main examples.

**Comment by gonsie** [comment]
Great! I'm glad we're simplifying the test cases so it will be easier to keep them up to date.

For testing, it is now expected that test_api_multiple passes all of serial/parallel start/restart, correct?

**Comment by adammoody** [comment]
Yes, I think it should pass serial/parallel and start/restart, although I don't think I tested all combinations.  Assuming the tests work, it's ready to merge.

**Comment by gonsie** [comment]
I updated the cmake (marking that we don't expect the serial restart to fail). Let's see what bamboo says before we merge this.

**Pull request merged**
