### PR TITLE
Change the line-continuation style in test_ckpt.F to F90-style

### PR DESCRIPTION
**Pull request by robertkb**
Spack really wants to build this file using the Fortran 90 compiler, rather than F77. The IBM xlf90 compiler does not accept F77-style line continuation, so change the instances to use the F90 "&".

### CODE REVIEW

**Comment by robertkb** [comment]
Works on lassen, fails on quartz... 
Quartz is using gfortran for both F77 and F90. When gfortran sees the .F extension, it assumes F77, and flags the line continuations because they are not F77 standard.
One fix:
- Change file extension to .F90
- Change the roughly 10 references to test_ckpt.F to test_ckpt.F90

Changing the file name in git will most likely cause the change log for test_ckpt.F to disappear. Git can sometimes find the old history if you use the --follow flag, but it is reportedly not reliable.

**Comment by adammoody** [comment]
Thanks, @robertkb .  Yes, let's create a version of this file with the F90 extension to straighten out the compilers.  If the ``--follow`` flag works with ``git mv``, that's good, but if not it's fine if we lose the history on this file.

For our CI tests longer term, it'd be nice to test compile/link for both F77 and F90 compilers.  For XL, we 'll check that ``xlf`` and ``xlf90`` can each compile and link with SCR.  That might mean we need to create different source files with different extensions, sort of like how we have a ``test_api.c`` for C and ``test_ckpt.cpp`` for C++.  This could be done as a separate step.

**Comment by robertkb** [comment]
I updated the cmake build to use the $(MPIF77) compiler to build the fortran test, and added a version of the test for F90. The cmake build appears to work on lassen and quartz,  but I still need to test the spack build.

**Comment by robertkb** [comment]
I think it is all working on quartz and lassen. I plan to test some more situations, but I'd appreciate other people trying it with their setup.

**Comment by robertkb** [comment]
I don't think this will interact with Roland's Fortran changes, but I plan to take a look.

**Review by CamStan — APPROVED** [review]

**Comment by adammoody** [comment]
Thanks @robertkb .  I'll go ahead and get this merged.  And thanks for reviewing it, @CamStan .

**Pull request merged**
