### PR TITLE
Configuration and modifications to enable gitlab CI testing using the ctest harness

### PR DESCRIPTION
**Pull request by robertkb**
CI testing is configured for catalyst, quartz, and lassen. 

Elsa, please add any other reviewers who would be interested in seeing this.

The CI testing is currently set up to be run manually from the Gitlab CI web interface. I'm not sure what testing workflow the team wants to eventually use (e.g. automatic with every commit, periodically, manually.) so we need to discuss that.

I think I might review where the CI testing builds the code. Given that home dirs are shared across the three systems, I've got some hard-coded paths for machine architectures, so different builds don't step on each other if occurring simultaneously. There should be a better way to do that.

I am running on the machines pbatch queues, since they seem to get better turnaround for the small test node counts that the debug queues. The automated tests will time out if the run does not start quickly enough, but switching to pbatch gets around that, for now. I don't know if Gitlab has a way to check for runner availability, but that would be the cleaner way to do that.

### CODE REVIEW

**Comment by robertkb** [comment]
I think I may have accidentally pulled in https://github.com/LLNL/scr/pull/162/commits/cf763edd49a2fff57d5f9b4297bcfa55e6da869f from the master branch rather than develop. I think I reverted the changed file, but I might look in to reverting the commit, to clean up the log.

**Comment by CamStan** [comment]
Wrong button...

**Comment by robertkb** [comment]
Rebased from all the latest updates in LLNL:develop, and cleaned up my testing script commits.
Builds are working on catalyst, but there are some issues on lassen and quartz. Still investigating.

**Comment by robertkb** [comment]
Last I checked, some tests were failing (its a bit of a moving target), but the testing code is working and ready to go. I'm not allowed to merge. What is the procedure for doing that?

**Comment by gonsie** [comment]
Everything looks great to me. If you are happy with it, I’m happy to do the merge.

**Comment by robertkb** [comment]
Please merge. Thanks.

**Pull request merged**
