### PR TITLE
enforce one-to-one mapping of id-to-name

### PR DESCRIPTION
**Pull request by adammoody**
While testing the restart loop and forcing checkpoints to be bad so that SCR would fetch the next most recent checkpoint, I came across an old bug in our index metadata.  This file resides in the prefix directory to record the list of datasets on the parallel file system.  In short, it was possible and somewhat typical to end up with multiple and inconsistent entries in the index for a given dataset id value.

This was a desired feature when SCR was creating the dataset directories on the parallel file system.  One could flush multiple copies of the same checkpoint, where each lived in its own directory.  Then if one copy of a particular checkpoint was corrupted, one could try another copy of the same checkpoint if available before falling back to try an older checkpoint.

However, now that directory layout is under control of the user, we typically will just have one copy of each checkpoint.  A re-flushed checkpoint will typically overwrite an existing one in the same location.  Instead, what is more typical is for the app and SCR to get out of sync so that dataset id may get used again but for a different checkpoint.  This ends up corrupting the metadata file so that a single dataset id refers to two distinct checkpoints.

The fix here is to enforce a one-to-one mapping of dataset id to name, rather than the one-to-many that used to exist.  To simplify the code. this changes the index file format in a way that is not backwards compatible, meaning any users who update to this new version but have an existing index file will fail.  If needed, we could do this change in a way that is backwards compatible or we could write a converter.

Resolves https://github.com/LLNL/scr/issues/175

This PR also updates scr_complete_output to return SCR_FAILURE if any process sets valid=0:

Resolves https://github.com/LLNL/scr/issues/173

This modifies SCR_GLOBAL_RESTART to change the fetch to use bypass, allowing an application to use the SCR restart API even with the global restart option.  This allows any process to read any file in its checkpoint during a restart.  That's often necessary in applications that can restart with a different number of processes than were used to write the original checkpoint.

Resolves https://github.com/LLNL/scr/issues/182

While at it, I was looking at tweaking our scr_index output.  We use a ```*``` in our scr_index list of checkpoints to mark the current checkpoint, similar to how git labels the current branch.  This provides an ```ls``` like listing, where the NAME field will be the most useful bit to users.

Do people have a preference between these?
```
>>: $scrbin/scr_index 
   DSET VALID FLUSHED              NAME
*     6 YES   2020-05-09T13:01:38 ckpt.6
      5 YES   2020-05-09T13:01:38 ckpt.5
```
```
>>: $scrbin/scr_index 
  DSET VALID FLUSHED             CUR NAME
     6 YES   2020-05-09T13:01:38   * ckpt.6
     5 YES   2020-05-09T13:01:38     ckpt.5
```
```
>>: $scrbin/scr_index
CUR   DSET VALID FLUSHED             NAME
 *       6 YES   2020-05-13T11:37:36 ckpt.6
         5 YES   2020-05-13T11:37:36 ckpt.5
```
```
>>: $scrbin/scr_index
CUR DSET VALID FLUSHED             NAME
  *    6 YES   2020-05-13T11:37:36 ckpt.6
       5 YES   2020-05-13T11:37:36 ckpt.5
```
```
>>: $scrbin/scr_index
  DSET CUR VALID FLUSHED             NAME
     6  *  YES   2020-05-13T11:37:36 ckpt.6
     5     YES   2020-05-13T11:37:36 ckpt.5
```

### CODE REVIEW

**Comment by adammoody** [comment]
Bumped the file format version number and added a check
```
>>: $scrbin/scr_index
SCR v1.2.0 ERROR: opal63: Found file format version 1 but expected 2 in index file: /tmp/install/share/scr/examples/.scr/index.scr @ /tmp/scr/src/scr_index_api.c:161
SCR v1.2.0 ERROR: opal63: Failed to read index file in /tmp/install/share/scr/examples @ tmp/scr/src/scr_index.c:1820
```

**Comment by adammoody** [comment]
For reference, here is what the current index file looks like:
```
  VERSION
    2
  CURRENT
    ckpt.6
  NAME
    ckpt.6
      DSET
        6
    ckpt.5
      DSET
        5
  DSET
    6
      FLUSHED
        2020-05-13T12:36:18
      COMPLETE
        1
      DSET
        ID
          6
        NAME
          ckpt.6
        FLAG_CKPT
          1
        FLAG_OUTPUT
          0
        CREATED
          1589398578343491
        USER
          user1
        JOBNAME
          testing_job
        JOBID
          106817
        CKPT
          6
        FILES
          4
        SIZE
          2097186
        COMPLETE
          1
    5
      DSET
        COMPLETE
          1
        SIZE
          2097186
        FILES
          4
        CKPT
          5
        JOBID
          106817
        JOBNAME
          testing_job
        USER
          user1
        CREATED
          1589398578270328
        FLAG_OUTPUT
          0
        FLAG_CKPT
          1
        NAME
          ckpt.5
        ID
          5
      COMPLETE
        1
      FLUSHED
        2020-05-13T12:36:18
```

**Comment by CamStan** [comment]
> Do people have a preference between these?

I like option 2 the most, and then 4.

**Comment by adammoody** [comment]
Well, just realized I'm not quite at one-to-one yet.  I changed a many-to-many to a one-to-many, so that an ID can refer to at most one checkpoint name but turns out a given checkpoint name can still have multiple IDs.  There's still a bit more work and thought to get down to one-to-one.  Working on it...

**Comment by adammoody** [comment]
> 
> 
> Well, just realized I'm not quite at one-to-one yet. I changed a many-to-many to a one-to-many, so that an ID can refer to at most one checkpoint name but turns out a given checkpoint name can still have multiple IDs. There's still a bit more work and thought to get down to one-to-one. Working on it...

Solution used here was delete any dataset of the same name that may already exist in the index file.  This is done as late as possible so we don't trash the existing dataset until we're just about to replace it.  It's done at the start of the flush, rather than the Start_output call.

**Pull request merged**
