### PR TITLE
scr_param: escapes braces in regex for embedded variables

### PR DESCRIPTION
**Pull request by rhaas80**
Also adds a unit test for scr_param.pm functionality.

This is a continuation / fixup of: https://github.com/LLNL/scr/pull/104

BTW should this go into master or components (neither one will apply cleanly right now)?

### CODE REVIEW

**Comment by adammoody** [comment]
Thank you, @rhaas80 .  It may be good to add this to both, but I'd start with the components branch.  Eventually, the plan is to shift SCR fully on to the components branch, but it's not quite ready and there are people who are dependent on the master branch.  It'll come down to whether those customers require this functionality in master before the switch is made.

**Comment by rhaas80** [comment]
* Rebased onto develop.
* added C code for multi-env variables expansion. C code testing is currently in `test_config` of [rhaas80/scr:rhaas/scr_param_set](https://github.com/rhaas80/scr/tree/rhaas/scr_param_set) in commit d0b328e which could be easily moved into `test_api.c` as far as I can see

**Comment by rhaas80** [comment]
@gonsie thank you for the review.

The script apparently used to require it at one point. There is a commented out line
```
#use lib '@X_DATADIR@/scr';
```
which would have required configuration. This was replaced by
```
use lib "../common"
```
which is not really much good as it assumes that the script is called from a particular location. The commented out form is what most other scripts use (eg `scr_env.in`).

However right now `test_scr_param` is not copied into build or run as part of the tests at all (though I do found it in older non-clean copies of my build directory). Likely I messed up files while merging / trying to clean up history. I will have to go  and fix the script so that it is actually called as part of ctest.

**Comment by rhaas80** [comment]
Alright. Now (46bb18b) `test_scr_param` is no longer preprocessed, and runs automatically as part of `make check` and via `ctest`. It also now checks some more things such as reading a `SCR_CONF_FILE`.

**Comment by adammoody** [comment]
Thanks, @rhaas80 !

**Pull request merged**
