### PR TITLE
Add developer documentation

### PR DESCRIPTION
**Pull request by CamStan**
### Summary
This adds a second set of documentation for developers. It keeps them in a separate folder to allow for a different url and thus a different pdf to be generated so that the developer docs are not distributed to users.

Also adds the doc build status badges to the README.

These files were converted from our .tex files. So if those files were out-of-date, these will be as well. I didn't read through them very thoroughly to check for incorrect content as SCR is still new to me. 

### Testing
Built off my own instance of ReadTheDocs which can be viewed [here](https://camstan-test-docs-scrdev.readthedocs.io).
The url for our docs is [SCR-dev.ReadTheDocs.io](https://scr-dev.readthedocs.io) which is currently being built off this branch. The rendered version can be viewed there. Once merged, this can be updated to build off master. Please look over it to see if anything should be changed.

### Motivation
This was my Hackathon project that I figured I'd tackle at @gonsie's request. Our .tex files were converted to .rst files using Pandoc and some images had to be converted as well. This went fairly smoothly other than the cross-document references didn't convert properly and needed to be manually edited.

### CODE REVIEW

**Comment by gonsie** [comment]
@kosinovsky this in the PR with the developer documenation. Once this is merged the docs will be in the `doc-dev` directory.

**Comment by adammoody** [comment]
Thanks @CamStan !  That looks like a ton of work.  Thanks for taking that on as a hackathon project!

Looks good to me.  Ready to merge?

**Comment by adammoody** [comment]
This developer guide is mostly correct for the master branch of scr.  It's difficult to keep up-to-date, so it naturally falls behind.  I can at least say that it was an accurate picture of the code base at some point in the past, but things now may work a little differently.  Just be aware if you're reading through it and trying to match it to the code.

**Comment by CamStan** [comment]
Docs are always hard to keep up to date. At least with it in the repo here it should be easier to update any discrepancies as we come across them.

@adammoody, yeah, should be good to merge.

**Pull request merged**
