### PR TITLE
add new log params to no app check

### PR DESCRIPTION
**Pull request by adammoody**
This adds the new SCR_LOG parameters to the no app check.

### CODE REVIEW

**Comment by adammoody** [comment]
@rhaas80 , I added the new LOG parameters to the no app check here.  I also did a sweep of style changes.  While doing that, I found two items I wanted to run by you:
1) It looked like if the ```scr_app_hash == NULL```, the file was being opened but not closed.  I'm guessing we should close the file.  I fixed that.
2) Do we want to create the file at all if ```scr_app_hash == NULL```?  I haven't looked at the rest of the code with that in mind.  If we can skip the file creation in that case, we could put a check for ```scr_app_hash == NULL``` and the top of the function and bail out right away.  Then we could yank the body of the function out one level of indentation.

**Comment by adammoody** [comment]
@rhaas80 , i forgot to bring this up on our call today.  Does this make sense?

**Comment by rhaas80** [comment]
Might be best to create an empty file so that an old file and its content do not stay around.

**Comment by adammoody** [comment]
Ah, really good point.  Yes, let me keep things so it writes an empty file.  Thanks.

**Pull request merged**
