### PR TITLE
Update test_ckpt.C

### PR DESCRIPTION
**Pull request by tonyhutter**
- Rename test_ckpt.C -> test_ckpt.cpp
- Update it so it can be easily used as C code as well.
- Allow it to take in an argument for checkpoint size in MB

These changes will help me with testing in #163.

### CODE REVIEW

**Comment by adammoody** [comment]
Hi @tonyhutter , we had added a C++ test intentionally after we found out one time that C++ codes could not easily use SCR.  At that time, we were missing ```extern "C"``` statements.  It's alright to have a C version, we'll want to keep a C++ program, too.

**Comment by tonyhutter** [comment]
@adammoody thanks for the info.  My latest push renames it `test_ckpt.cpp` and I added some trivial C++isms to get it to build as C++.

**Comment by adammoody** [comment]
Looks good to me.  Thanks.  This ready for merge, @tonyhutter?

**Comment by tonyhutter** [comment]
Almost, let me update these additional references to test_ckpt.C
```
examples/test_ckpt.cpp:1:// mpig++ -g -O0 -I../src -o test_ckpt_C test_ckpt.C -L/usr/local/tools/scr-1.1/lib -lscr
examples/makefile.examples.in:30:test_ckpt_C: test_ckpt.C
examples/makefile.examples.in:31:	$(MPICXX) $(OPT) $(CXXFLAGS) $(INCLUDES) -o test_ckpt_C test_ckpt.C \
build/examples/makefile.examples:30:test_ckpt_C: test_ckpt.C
build/examples/makefile.examples:31:	$(MPICXX) $(OPT) $(CXXFLAGS) $(INCLUDES) -o test_ckpt_C test_ckpt.C \
```

**Comment by tonyhutter** [comment]
Should be good now

**Pull request merged**
