### PR TITLE
Add basic Flux support

### PR DESCRIPTION
**Pull request by ofaaland**
Add FLUX value to SCR_RESOURCE_MANAGER cmake property
Read Flux Job ID from environment in scr_env_jobid()
Add FLUX subdirectory and stubs for shell scripts
 - since these are about to be replaced with a python script,
 it was deemed a waste of time to implement Flux versions.

Passed simple testing on elmerfudd with -DSCR_RESOURCE_MANAGER=FLUX

### CODE REVIEW

**Comment by ofaaland** [comment]
@adammoody please take a look, thanks.

**Comment by adammoody** [comment]
Thanks @ofaaland .  Looks good to me.

Since we're about to stamp a v3.0 release, let's merge this into the develop branch after the release.  In the meantime, could you create a "flux" branch from develop so we can merge this PR into the flux branch.  We can then later merge flux into develop sometime after the release.

**Comment by ofaaland** [comment]
Hi @adammoody that makes sense.  Re: the flux branch, it looks like permissions don't allow me to create a branch in the scr repo.

**Comment by adammoody** [comment]
Ah, ok.  We may need to add you to some list.  I went ahead and created a flux branch and merged your PR into that.

**Pull request merged**
