### PR TITLE
handle IBM XL compiler for Fortran bindings

### PR DESCRIPTION
**Pull request by rhaas80**
This pull request adds support for the IBM xl compiler which does not, by default, add an underscore `_` at the end of routine names. 

Support is added by

1. detecting the presence of the compiler by checking the `__ibmxl__` preprocessor define that the compiler defines (even for Fortran code) when passing source code through cpp
2. adding a `FORT_NAME(name)` function like macro that either appends or does not append an underscore `_` to the name
3. moving the conflicting `scr_have_restart` global variable into a static variable of the same name in `scr.c` which is the only file where it is actually used

a second change is replacing `#ifdef IBM` by `#idfef __ibmxl__` in `scr_ckpt.F` to handle the call to the non-standard `flush` function.

To test on lassen run:
```bash
git clone -b rhaas/fortran https://github.com/rhaas80/scr
cd scr
CC=xlc CXX=xlC FC=xlf ./bootstrap.sh
mkdir build
cd build
CC=xlc CXX=xlC FC=xlf cmake -DCMAKE_INSTALL_PREFIX=$PWD/../install ..
make
```

### CODE REVIEW

**Comment by adammoody** [comment]
Thanks @rhaas80 .  This is great!

For one extension, in the FORTNAME macro, I'm thinking we could also provide a new CMake option to let users tell SCR how many underscores to use: 0, 1, or 2.  We could use that option if given.

**Comment by rhaas80** [comment]
That is certainly doable and giving users the option to overwrite the automatism would be a very good idea I think. 

Note that one may have to be careful how much generality one wants to support (and should document that level). Looking at (just) the gfortran underscore options (https://gcc.gnu.org/onlinedocs/gfortran/Code-Gen-Options.html) one could consider: 0, 1, 2 trailing underscores. Depending on the function name itself eg `foo_bar` turns into:

- no options: `foo_bar_`
- `-fno-underscoring`: `foo_bar`
- `-fsecond-underscore`: `foo_bar__`

and `foo` turns into:

- no options: `foo_`
- `-fno-underscoring`: `foo`
- `-fsecond-underscore`: `foo_`

i.e. (as documented) the `__` is only appended if the Fortran subroutine name already contained an undersore which is not something that can be done with just the C preprocessor (or if it can then I suspect it is quite ugly in the generic case). For SCR with names like `scr_xxx` we will always add the underscores and will be fine.

Similarly I did not make any attempt to handle Fortran compilers that may use all uppercase function names. Most (all by now?) compilers use lowercase. Apparently some Cray compilers (https://www.ibiblio.org/pub/languages/fortran/ch1-11.html) may have used all upppercase (though thankfully current Cray no longer do so). 

Looking at my code: I should test this on gfortran. Namely the `foo ## _` syntax requires a C89 cpp and will not work with a `--traditiional` cpp (which I have seen used with Fortran) where one would need to do something like `foo/**/_` since a `--traditional` cpp is string based rather than token based (and does not know of `##`). A C89 cpp on the other hand will replace `/**/` by an equivalent number of spaces (which a sufficiently F77 compiler may ignore but a free-form F90 compiler must respect).

**Comment by rhaas80** [comment]
Ok, so gfortran does not like `##` namely this code:

```Fortran
#define f(a) a##_

subroutine foo(a_)
  implicit none
  integer :: a_
  f(a) = 1
end subroutine
```
fails with gfortran:
```
$ gfortran -c foo.F90
foo.F90:6.2:

  a##_ = 1
  1
Error: Unclassifiable statement at (1)
```
while
```Fortran
#define f(a) a/**/_

subroutine foo(a_)
  implicit none
  integer :: a_
  f(a) = 1
end subroutine
```
works with both gfortran and xlf (lassen) but fails with ifort (catalyst) which wants the `##` flavor.

:-(

**Comment by rhaas80** [comment]
This can (probably) be worked around with compiler defines (ugly...) namely:

* xl `__ibmxl__` (either one)
* GNU `__GFORTRAN__` (`/**/`)
* intel `__INTEL_COMPILER` (`##`)
* Cray `_CRAYFTN` (`/**/`)
* PGI `__PGI` (`##`)

not sure about other compilers we may care about

**Comment by adammoody** [comment]
@rhaas80 , how is this one coming along?  I remember you had identified another item that you wanted to look at, but I also know you'll be busy with other responsibilities soon if not already.  This is good work.  It'd be good to merge in what you've done even if it's not quite complete.

**Comment by adammoody** [comment]
@rhaas80 , thanks again for putting this together.  I'd like to merge this in, since it solves the XL compiler problem.  I'll touch it up to bring it up to date withe the latest develop branch.

**Pull request closed without merging**
